import { Pokemon } from 'src/app.model';

export const mockPokemonList = {
  list: [
    {
      '#': '1',
      Name: 'Bulbasaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '318',
      HP: '45',
      Attack: '49',
      Defense: '49',
      'Sp. Atk': '65',
      'Sp. Def': '65',
      Speed: '45',
      Generation: '1',
      Legendary: 'False',
    },
    {
      '#': '2',
      Name: 'Ivysaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '405',
      HP: '60',
      Attack: '62',
      Defense: '63',
      'Sp. Atk': '80',
      'Sp. Def': '80',
      Speed: '60',
      Generation: '1',
      Legendary: 'False',
    },
    {
      '#': '3',
      Name: 'Venusaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '525',
      HP: '80',
      Attack: '82',
      Defense: '83',
      'Sp. Atk': '100',
      'Sp. Def': '100',
      Speed: '80',
      Generation: '1',
      Legendary: 'False',
    },
  ],
  count: 1000,
  offset: 0,
  total: 3,
};

export const mockPokemonListOffset = {
  list: [
    {
      '#': '2',
      Name: 'Ivysaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '405',
      HP: '60',
      Attack: '62',
      Defense: '63',
      'Sp. Atk': '80',
      'Sp. Def': '80',
      Speed: '60',
      Generation: '1',
      Legendary: 'False',
    },
    {
      '#': '3',
      Name: 'Venusaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '525',
      HP: '80',
      Attack: '82',
      Defense: '83',
      'Sp. Atk': '100',
      'Sp. Def': '100',
      Speed: '80',
      Generation: '1',
      Legendary: 'False',
    },
  ],
  count: 2,
  offset: 1,
  total: 2,
};

export const mockPokemon = {
  '#': '1',
  Name: 'Bulbasaur',
  'Type 1': 'Grass',
  'Type 2': 'Poison',
  Total: '318',
  HP: '45',
  Attack: '49',
  Defense: '49',
  'Sp. Atk': '65',
  'Sp. Def': '65',
  Speed: '45',
  Generation: '1',
  Legendary: 'False',
};

export const mockedPokemonList = {
  list: [
    {
      '#': '1',
      Name: 'Bulbasaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '318',
      HP: '45',
      Attack: '49',
      Defense: '49',
      'Sp. Atk': '65',
      'Sp. Def': '65',
      Speed: '45',
      Generation: '1',
      Legendary: 'False',
    },
    {
      '#': '2',
      Name: 'Ivysaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '405',
      HP: '60',
      Attack: '62',
      Defense: '63',
      'Sp. Atk': '80',
      'Sp. Def': '80',
      Speed: '60',
      Generation: '1',
      Legendary: 'False',
    },
    {
      '#': '3',
      Name: 'Venusaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '525',
      HP: '80',
      Attack: '82',
      Defense: '83',
      'Sp. Atk': '100',
      'Sp. Def': '100',
      Speed: '80',
      Generation: '1',
      Legendary: 'False',
    },
  ] as Pokemon[],
  count: 1000,
  offset: 0,
  total: 3,
};

export const mockedPokemonListWithOffset = {
  list: [
    {
      '#': '2',
      Name: 'Ivysaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '405',
      HP: '60',
      Attack: '62',
      Defense: '63',
      'Sp. Atk': '80',
      'Sp. Def': '80',
      Speed: '60',
      Generation: '1',
      Legendary: 'False',
    },
    {
      '#': '3',
      Name: 'Venusaur',
      'Type 1': 'Grass',
      'Type 2': 'Poison',
      Total: '525',
      HP: '80',
      Attack: '82',
      Defense: '83',
      'Sp. Atk': '100',
      'Sp. Def': '100',
      Speed: '80',
      Generation: '1',
      Legendary: 'False',
    },
  ] as Pokemon[],
  count: 2,
  offset: 1,
  total: 3,
};

export const originalMockCsv = `#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary\r\n1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False\r\n2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False\r\n3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False\r\n`;
